# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  skdvcsserver:
    image: skdvcsserver
    build:
      context: .
      dockerfile: SKD.Server/Dockerfile
    ports:
      - 5100
      - 5101
