# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  skdvcs:
    image: paulyk/skd-server
    build:
      context: .
      dockerfile: SKD.Server/Dockerfile
    container_name: skd-server
    ports:
      - 5100:80
      - 5101:443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Default=server=mssql;database=skd;uid=sa;pwd=DevOnlyPassword119
    volumes:
      - ~/.vsdbg:/remote_debugger:rw



